# Generated by Django 5.2.2 on 2025-08-05 20:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(db_column='userID', primary_key=True, serialize=False)),
                ('username', models.CharField(db_column='userName', max_length=30, unique=True)),
                ('password', models.CharField(db_column='PW', max_length=255)),
                ('screen_name', models.CharField(db_column='screenName', max_length=50)),
                ('sex', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], db_column='sex', max_length=1, null=True)),
                ('height', models.DecimalField(blank=True, db_column='height', decimal_places=2, max_digits=6, null=True)),
                ('weight', models.DecimalField(blank=True, db_column='weight', decimal_places=2, max_digits=6, null=True)),
            ],
            options={
                'db_table': 'Users',
            },
        ),
        migrations.CreateModel(
            name='WorkoutType',
            fields=[
                ('workout_type_id', models.AutoField(db_column='workoutTypeID', primary_key=True, serialize=False)),
                ('workout_name', models.CharField(db_column='workoutName', max_length=50, unique=True)),
            ],
            options={
                'db_table': 'WorkoutTypes',
            },
        ),
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('workout_id', models.AutoField(db_column='workoutID', primary_key=True, serialize=False)),
                ('duration', models.DurationField(db_column='duration')),
                ('workout_date', models.DateField(db_column='workoutDate')),
                ('rpe', models.PositiveSmallIntegerField(blank=True, db_column='RPE', null=True)),
                ('notes', models.TextField(blank=True, db_column='notes', null=True)),
                ('user', models.ForeignKey(db_column='userID', on_delete=django.db.models.deletion.CASCADE, related_name='workouts', to='api.user')),
                ('workout_type', models.ForeignKey(db_column='workoutType', on_delete=django.db.models.deletion.CASCADE, related_name='workouts', to='api.workouttype')),
            ],
            options={
                'db_table': 'Workouts',
                'indexes': [models.Index(fields=['user'], name='indexUserDate')],
            },
        ),
        migrations.CreateModel(
            name='ScheduledWorkout',
            fields=[
                ('scheduled_workout_id', models.AutoField(db_column='scheduledWorkoutID', primary_key=True, serialize=False)),
                ('duration', models.DurationField(blank=True, db_column='duration', null=True)),
                ('scheduled_date', models.DateField(db_column='scheduledDate')),
                ('user', models.ForeignKey(db_column='userID', on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_workouts', to='api.user')),
                ('workout_type', models.ForeignKey(db_column='workoutType', on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_workouts', to='api.workouttype')),
            ],
            options={
                'db_table': 'ScheduledWorkouts',
                'indexes': [models.Index(fields=['user', 'scheduled_date'], name='indexScheduledDate')],
            },
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('goal_id', models.AutoField(db_column='goalID', primary_key=True, serialize=False)),
                ('duration', models.DurationField(blank=True, db_column='duration', null=True)),
                ('notes', models.TextField(blank=True, db_column='notes', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='createdAt')),
                ('completed_at', models.DateTimeField(blank=True, db_column='completedAt', null=True)),
                ('is_complete', models.BooleanField(db_column='isComplete', default=False)),
                ('user', models.ForeignKey(db_column='userID', on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='api.user')),
                ('goal_type', models.ForeignKey(blank=True, db_column='goalType', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='api.workouttype')),
            ],
            options={
                'db_table': 'Goals',
                'indexes': [models.Index(fields=['user', 'goal_type', 'is_complete'], name='indexGoalStatus')],
            },
        ),
    ]
